### ISSUE TITLE
Feature suggestion: Real-time query qarameter URL update

### ISSUE THREAD

**Issue by Hamdan-Khan** [Hamdan-Khan/API-Playground#1]
## Current Behavior

Currently, there are two ways to add query parameters:
1. Directly typing them in the URL input field (e.g., `https://dummyapi.com?query1=abc&query2=xyz`)
2. Using the key-value input fields and clicking "Add query" button, which then updates the URL

## Desired Behavior

- Query parameters should appear in the URL input field in real-time as users type in the key-value input fields
- No need to click an "Add query" button
- The URL should update dynamically while maintaining proper URL 
- Should handle empty values and special characters appropriately

**Comment by KAMAL-02** [comment]
Kindly assign i would like to work on it

**Comment by KAMAL-02** [comment]
Close the issue as it got fixed already
