### ISSUE TITLE
Failed input validation results in unexpected errors

### ISSUE THREAD

**Issue by Asterki** [Hamdan-Khan/API-Playground#2]
**Describe the bug**
Failed input validation results in unexpected errors

**To Reproduce**
1. Go to "Body"
2. Insert any invalid JSON document
3. Press send request

**Expected behavior**
The error be handled and shown to the user

**Screenshots**
![image](https://github.com/user-attachments/assets/ad412063-edf4-48e4-8db1-0f49a319955e)

**Comment by Asterki** [comment]
I'm working on a fix that will be published to a new pull request.

**Comment by Asterki** [comment]
Pull request published, see #3 for details

**Comment by Hamdan-Khan** [comment]
Merged.
